# Generated by Django 5.2.5 on 2025-09-04 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
        ("clients", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="audit",
            name="uniq_audit_company_reference",
        ),
        migrations.AddConstraint(
            model_name="audit",
            constraint=models.UniqueConstraint(
                fields=("company", "reference"), name="uniq_audit_company_reference"
            ),
        ),
    ]
