# Generated by Django 5.2.5 on 2025-09-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Listelerde görünecek kısa ad",
                        max_length=120,
                        unique=True,
                        verbose_name="Kısa Ad",
                    ),
                ),
                (
                    "legal_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Unvan"),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Vergi No"
                    ),
                ),
                (
                    "staff_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Personel Sayısı"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Kuruluş Yılı"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="companies_c_name_2d8260_idx"),
                    models.Index(
                        fields=["vat_number"], name="companies_c_vat_num_8242f1_idx"
                    ),
                ],
            },
        ),
    ]
